# Generated by Django 5.0.3 on 2024-08-04 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('irctc', '0002_irctcadmin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IRCTCADMIN',
            new_name='Trains',
        ),
        migrations.RenameModel(
            old_name='IRCTC',
            new_name='Users',
        ),
    ]
